services:
  - type: web
    name: django-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings
      - key: PYTHON_VERSION
        value: 3.10
      - key: DB_NAME
        value: invoice_management_db
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        value: root
      - key: DB_HOST
        value: localhost
      - key: DB_PORT
        value: 5432
